/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import org.json.JSONString;
import org.json.JSONObject;
import org.json.JSONTokener;
import java.io.FileInputStream;
import java.io.PrintWriter;
import java.io.File;
import java.util.Enumeration;
import java.io.Serializable;

/**
 *
 * @author binhonglee
 */
public class SampleUI extends javax.swing.JFrame {

    /**
     * Creates new form SampleUI
     */
    public SampleUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLbl = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        symptomsLbl = new javax.swing.JLabel();
        symptomsTF = new javax.swing.JTextField();
        allergiesLbl = new javax.swing.JLabel();
        allergiesTF = new javax.swing.JTextField();
        medLbl = new javax.swing.JLabel();
        medTF = new javax.swing.JTextField();
        pastLbl = new javax.swing.JLabel();
        pastTF = new javax.swing.JTextField();
        lastLbl = new javax.swing.JLabel();
        lastTF = new javax.swing.JTextField();
        eventsLbl = new javax.swing.JLabel();
        eventsTF = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        reloadBtn = new javax.swing.JButton();
        ssnLbl = new javax.swing.JLabel();
        ssnTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameLbl.setText("Name");

        nameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTFActionPerformed(evt);
            }
        });

        symptomsLbl.setText("Symptoms");

        symptomsTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                symptomsTFActionPerformed(evt);
            }
        });

        allergiesLbl.setText("Allergies");

        allergiesTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allergiesTFActionPerformed(evt);
            }
        });

        medLbl.setText("Medications");

        medTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medTFActionPerformed(evt);
            }
        });

        pastLbl.setText("Past Medical History");

        pastTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pastTFActionPerformed(evt);
            }
        });

        lastLbl.setText("Last Oral History");

        lastTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastTFActionPerformed(evt);
            }
        });

        eventsLbl.setText("Events leading up to injury");

        eventsTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventsTFActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        reloadBtn.setText("Retrieve");
        reloadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadBtnActionPerformed(evt);
            }
        });

        ssnLbl.setText("SSN");

        ssnTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssnTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eventsLbl)
                            .addComponent(eventsTF, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastLbl)
                            .addComponent(lastTF, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pastLbl)
                            .addComponent(pastTF, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(medLbl)
                            .addComponent(medTF, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(allergiesLbl)
                            .addComponent(allergiesTF, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(symptomsLbl)
                            .addComponent(symptomsTF, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLbl)
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ssnLbl)
                            .addComponent(ssnTF, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 46, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(reloadBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(nameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(symptomsLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(symptomsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allergiesLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allergiesTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(medLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(medTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pastLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pastTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eventsLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eventsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ssnLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ssnTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reloadBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTFActionPerformed

    private void symptomsTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_symptomsTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_symptomsTFActionPerformed

    private void allergiesTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allergiesTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allergiesTFActionPerformed

    private void medTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medTFActionPerformed

    private void pastTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pastTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pastTFActionPerformed

    private void lastTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastTFActionPerformed

    private void eventsTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventsTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventsTFActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        String ssn = ssnTF.getText();

        if (ssn.length() != 9)
        {
          ssnTF.setText("Invalid SSN. Please try again.");
          return;
        }

        String name = nameTF.getText();
        String symptoms = symptomsTF.getText();
        String allergies = allergiesTF.getText();
        String med = medTF.getText();
        String past = pastTF.getText();
        String last = lastTF.getText();
        String events = eventsTF.getText();

        JSONObject obj = new JSONObject();
        obj.put("Name", name);
        obj.put("Symptoms", symptoms);
        obj.put("Allergies", allergies);
        obj.put("Med", med);
        obj.put("Past", past);
        obj.put("Last", last);
        obj.put("Events", events);

        String jsonFileName = ssn + ".json";
        System.out.println(ssn.length());
        toJsonFile(jsonFileName, obj);
        cleanup();
        ssnTF.setText("Information saved successfully");
    }//GEN-LAST:event_saveBtnActionPerformed

    public void toJsonFile(String jsonFileName, JSONObject obj)
    {
      try
      {
        PrintWriter out = new PrintWriter(jsonFileName);

        out.println(obj.toString());
        out.close();
      }
      catch (Exception e)
      {
        System.out.println("Exception: " + e.getMessage());
      }
    }

    private void reloadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadBtnActionPerformed
      // TODO add your handling code here:
      String ssn = ssnTF.getText();
      if (ssn.length() != 9)
      {
        ssnTF.setText("Invalid SSN. Please try again.");
        return;
      }

      String jsonFileName = ssn + ".json";

      try
      {
        FileInputStream in = new FileInputStream(jsonFileName);
        JSONObject obj = new JSONObject(new JSONTokener(in));

        nameTF.setText(obj.getString("Name"));
        symptomsTF.setText(obj.getString("Symptoms"));
        allergiesTF.setText(obj.getString("Allergies"));
        medTF.setText(obj.getString("Med"));
        pastTF.setText(obj.getString("Past"));
        lastTF.setText(obj.getString("Last"));
        eventsTF.setText(obj.getString("Events"));

        in.close();
      }
      catch (Exception ex)
      {
        System.out.println("Exception importing from json: " + ex.getMessage());
        cleanup();
        ssnTF.setText("SSN record not found");
      }
    }//GEN-LAST:event_reloadBtnActionPerformed

    private void ssnTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssnTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssnTFActionPerformed

    public void cleanup()
    {
      nameTF.setText("");
      symptomsTF.setText("");
      allergiesTF.setText("");
      medTF.setText("");
      pastTF.setText("");
      lastTF.setText("");
      eventsTF.setText("");
      ssnTF.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SampleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SampleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SampleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SampleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SampleUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel allergiesLbl;
    private javax.swing.JTextField allergiesTF;
    private javax.swing.JLabel eventsLbl;
    private javax.swing.JTextField eventsTF;
    private javax.swing.JLabel lastLbl;
    private javax.swing.JTextField lastTF;
    private javax.swing.JLabel medLbl;
    private javax.swing.JTextField medTF;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel pastLbl;
    private javax.swing.JTextField pastTF;
    private javax.swing.JButton reloadBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel ssnLbl;
    private javax.swing.JTextField ssnTF;
    private javax.swing.JLabel symptomsLbl;
    private javax.swing.JTextField symptomsTF;
    // End of variables declaration//GEN-END:variables
}
